django_cancer_ml/mysite/myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"

urlpatterns = [
    path('', views.predict, name='prediction_page'),
     
     path('predict/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
]

django_cancer_ml/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='myapp'))
]

django_cancer_ml/mysite/myapp/models.py
from django.db import models

 
class PredResults(models.Model):
    #id = models.AutoField(primary_key=True)

    Age = models.FloatField()
    air_pollution = models.FloatField()
    alcohol_use = models.FloatField()
    genetic_risk = models.FloatField()
    chronic_lung_disease = models.FloatField()
 
    Level = models.CharField(max_length=30)

    def __str__(self):
        return self.Level

django_cancer_ml/mysite/myapp/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import PredResults

 

def predict(request):
    return render(request, 'predict.html')

 

def predict_chances(request):

    if request.POST.get('action') == 'post':

        # Receive data from client
        Age = float(request.POST.get('Age'))
        air_pollution = float(request.POST.get('air_pollution'))
        alcohol_use = float(request.POST.get('alcohol_use'))
        genetic_risk = float(request.POST.get('genetic_risk'))
        chronic_lung_disease = float(request.POST.get('chronic_lung_disease'))
 
        # Unpickle model C:\Users\TECHNICIAN\Desktop\CANCER-END-END\django_cancer_ml\mysite\new_model.pickle
        model = pd.read_pickle(r'C:\Users\TECHNICIAN\Desktop\CANCER-END-END\django_cancer_ml\mysite\new_model.pickle')
        #pd.to_pickle(model,)

        # Make prediction
        result = model.predict([[Age, air_pollution, alcohol_use, genetic_risk,chronic_lung_disease]])

        Level = result[0]

        PredResults.objects.create(Age=Age, air_pollution=air_pollution, alcohol_use=alcohol_use,
                                   genetic_risk=genetic_risk,chronic_lung_disease=chronic_lung_disease, Level=Level)

        return JsonResponse({'Level': Level, 'Age': Age,
                             'air_pollution': air_pollution, 'alcohol_use': alcohol_use, 
                             'genetic_risk': genetic_risk,'chronic_lung_disease':chronic_lung_disease},
                            safe=False)


def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults.objects.all()}
    return render(request, "results.html", data)

django_cancer_ml/mysite/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>CANCER prediction</title>
    </head>
    <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/results">DATABASE</a>
            </li>
          </ul>
        </div>
      </nav>
      

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

django_cancer_ml/mysite/templates/predict.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>  Age: <span id="sl"></span></div>
                <div> air_pollution: <span id="sw"></span></div>
                <div> alcohol_use: <span id="pl"></span></div>
                <div> genetic_risk: <span id="pw"></span></div>
                <div> chronic_lung_disease: <span id="cw"></span></div>

                
                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>CANCER Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="Age">Age</label>
                    <input type="number" step="0.1" class="form-control" id="Age" placeholder="Age in years" required>
                </div>
 
                <div class="form-group">
                    <label for="air_pollution">air_pollution  </label>
                    <input type="number" step="0.1" class="form-control" id="air_pollution" placeholder="air_pollution" required>
                </div>
                <div class="form-group">
                    <label for="alcohol_use">alcohol_use</label>
                    <input type="number" step="0.1" class="form-control" id="alcohol_use" placeholder="alcohol_use" required>
                </div>
                <div class="form-group">
                    <label for="genetic_risk">genetic_risk</label>
                    <input type="number" step="0.1" class="form-control" id="genetic_risk" placeholder="genetic_risk" required>
                </div>
                <div class="form-group">
                    <label for="chronic_lung_disease">chronic_lung_disease</label>
                    <input type="number" step="0.1" class="form-control" id="chronic_lung_disease" placeholder="chronic_lung_disease" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST', 
             

            url:'{% url "myapp:submit_prediction" %}',
            data:{
                Age:$('#Age').val(),
                air_pollution:$('#air_pollution').val(),
                alcohol_use:$('#alcohol_use').val(),
                genetic_risk:$('#genetic_risk').val(),
                chronic_lung_disease:$('#chronic_lung_disease').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("sl").innerHTML = json['Age']
                document.getElementById("sw").innerHTML = json['air_pollution']
                document.getElementById("pl").innerHTML = json['alcohol_use']
                document.getElementById("pl").innerHTML = json['genetic_risk']
                document.getElementById("pw").innerHTML = json['chronic_lung_disease']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

django_cancer_ml/mysite/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">   Age</th>
                <th scope="col">  air_pollution</th>
                <th scope="col">  alcohol_use</th>
                <th scope="col">  genetic_risk</th>
                <th scope="col"> chronic_lung_disease</th>
                 
                <th scope="col">Prediction</th>
 
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
 
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.Age }}</td>
                    <td>{{ data.air_pollution }}</td>
                    <td>{{ data.alcohol_use }}</td>
                    <td>{{ data.genetic_risk }}</td>
                    <td>{{ data.chronic_lung_disease }}</td>
                    <td>{{ data.Level }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}